image: php:7.4-cli

# services:
#   - mysql:5.7

stages:
  # - test
  - deploy

# unit_test:
#   stage: test
#   script:
#     - cp .env.example .env
#     - composer install
#     - php artisan key:generate
#     - php artisan migrate
#     - vendor/bin/phpunit

deploy_dev:
  stage: deploy
  script:
    - cd /home/adminhadoop/apps/amdalnet/
    - git reset --hard HEAD
    - git pull
    - docker-compose up -d
    - docker-compose exec -T laravel composer install
    - docker-compose exec -T laravel php artisan migrate
    - docker-compose exec -T laravel npm install
    - docker-compose exec -T laravel npm run production
    # - docker-compose restart laravel
  environment:
    name: staging
  when: on_success
  only:
    - master
  tags:
    - amdalnet

deploy_cloud:
  stage: deploy
  script:
    - echo "xxxx"
    - cd /var/www/amdalnet/
    - git reset --hard HEAD
    - git pull
    - composer install
    - php artisan migrate
    - npm install
    - npm run production
  environment:
    name: staging
  when: on_success
  only:
    - master
  tags:
    - cloud