image: php:7.4-cli

# services:
#   - mysql:5.7

stages:
  # - test
  - deploy

# unit_test:
#   stage: test
#   script:
#     - cp .env.example .env
#     - composer install
#     - php artisan key:generate
#     - php artisan migrate
#     - vendor/bin/phpunit

deploy_dev:
  stage: deploy
  script:
    - cd /home/adminhadoop/apps/amdalnet/
    - git reset --hard HEAD
    - git pull
  environment:
    name: staging
  when: on_success
  only:
    - master
  tags:
    - amdalnet
