version: "3"

services:
  laravel:
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # - ./docker/docker.env:/var/www/.env
    # ports:
    #   - "8000:8000"

    depends_on:
      - database
      - redis

  redis:
    image: redis:alpine

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
  database:
    image: postgres:13
    ports:
      - "6666:5432"
    environment:
      - "POSTGRES_PASSWORD=laravue"
      - "POSTGRES_USER=laravue"
      - "POSTGRES_DB=laravue"



